### ISSUE TITLE
Use in production ?

### ISSUE THREAD

**Issue by laruche** [LouisBertin/prestashop1.7-docker-lamp#1]
Bonjour Louis, 

je suis en train de migrer d'un hebergement mutualisé vers un VPS avec Caprover / Docker 
et je suis à la recherche d'un template pour gérer la production 

Utilises tu aussi ce template en production ? En particulier sur la gestion des dossiers image etc :) 

A te lire :)

**Comment by LouisBertin** [comment]
Bonjour @laruche!

J'utilise essentiellement cette config pour mes développements en local, afin de fit au maximum avec les environnements de production. 
De plus, j'évite d'utiliser https://hub.docker.com/r/prestashop/prestashop/ car l'image est un peu trop all-in-one pour moi. 

J'espère que j'ai répondu à la question ;)

**Comment by laruche** [comment]
Oui merci :)
Je vais essayer de faire un boilerplate pour ma prod 
car mon futur environnement est full docker :D

**Comment by LouisBertin** [comment]
Sympa comme environnement!

Je n'ai jamais déployé des Prestashop en production avec Docker, mais j'imagine qu'il faudrait jeter un coup d'oeil du côté de Bitnami : https://github.com/bitnami/bitnami-docker-prestashop ou encore l'image officiel de Prestashop.

**Comment by laruche** [comment]
Moi non plus on va tester :D 
mes premiers tests ont l'air de marcher ! 
Je suis en train de séparer les dossiers de travail (img / modules / theme /override ) dans des volumes différents avec des strategies différentes !

**Comment by LouisBertin** [comment]
À ce sujet @laruche,

J'ai déployé un Caprover sur l'un de mes serveurs pour mon usage personnel, j'ai setup une conf Caprover pour WinterCMS car je n'en ai pas trouvée online.. 

Ça pourra sûrement donner de l'inspiration pour la configuration Prestashop 😉

https://gist.github.com/LouisBertin/8f0fcb248d62f3e17960aee447736344
