### ISSUE TITLE
get picture of config Prestashop MailCatcher

### ISSUE THREAD

**Issue by webdevproformation** [LouisBertin/prestashop1.7-docker-lamp#2]
hello,

First, great depot !!! thanx a lot for sharing, the is the only docker achieve pour use with prestashop !! thanks a lot

in the .md document there is a link to a picture => https://camo.githubusercontent.com/20686f2ceafd7ad4eba0798718af10ef23ad2222de1c9d5cc0ada6c48520789a/68747470733a2f2f75706c6f61642e7661612e7265642f692f37706572792e706e67

it doesn't seem to work => it have this response => Invalid upstream response (403)

Could you give me the right link ? 

Best regards

**Comment by LouisBertin** [comment]
Hi!

Thanks for your message! I have changed the image in the README.md file.

Don't hesitate if you need anything else!
Regards,

**Comment by webdevproformation** [comment]
un grand merci !!! Excellente journée @ toi !!
